name: Deploy Config - Release

# Controls when the workflow will run.
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        required: true
        options:
          - DEV
          - QA
          - PERF
          - PROD
        default: DEV  # Set the default environment choice here
      choice:
        type: choice
        description: Select type of Business
        options:
          - Retail
        default: Retail  # Set the default choice here

jobs:
  unauthorized-user-check:
    if: ${{ !contains(fromJSON(vars.AUTHORIZED_WORKFLOW_DISPATCH_USERS), github.actor) }}
    runs-on: ubuntu-latest
    steps:
      - name: Failure message
        run: |
          echo "You are not authorized to trigger this workflow"
      - name: Abort workflow run
        run: exit 1
  echo-selections:
    runs-on: ubuntu-latest
    if: contains(fromJSON(vars.AUTHORIZED_WORKFLOW_DISPATCH_USERS), github.actor)
    steps:
      - name: Echo Selected Inputs
        run: |
          echo "Selected environment: ${{ github.event.inputs.environment }}"
          echo "Selected business type: ${{ github.event.inputs.choice }}"
          echo "user triggered workflow is ${{ github.actor }}"
